### ISSUE TITLE
Peer-peer code review  24/01/2023

### ISSUE THREAD

**Issue by Nkaleth** [banzaman/ES6-Todo-List#6]
https://github.com/banzaman/ES6-Todo-List.github.io/blob/104fe8b63139901feeaa5d63caf4eafbe0437325/src/index.js#L30
-Kindly declare the variables at the start of the script according to JavaScript best practices. Anything more to say, you did a very clean and good work!
-Kindly check your live demo, is not working.

**Comment by banzaman** [comment]
Thanks for the issue make an update soon.
